### ISSUE TITLE
Shortcut key stop and script file support

### ISSUE THREAD

**Issue by controlloli** [MysteriousJ/KeyboardRecorder#2]
1. Increase ease of use
2. Increase the script file for easy analysis and repeated use

**Comment by controlloli** [comment]
Looking forward to your reply

**Comment by MysteriousJ** [comment]
Good suggestions. I'll add them when I have a chance, though it might be a while.

**Comment by MysteriousJ** [comment]
Latest build allows setting a key binding for stopping playback, and saving/loading recordings in files.
